export const RENDER = {
  NODE_RADIUS: 16,
  NODE_STROKE_WIDTH: 2.5,
  EDGE_STROKE_WIDTH: 2,
  LABEL_FONT_SIZE: 12,
  LABEL_PADDING_X: 8,
  LABEL_BORDER_RADIUS: 4,
  HASH_FONT_SIZE: 10,
  ZOOM_MIN: 0.3,
  ZOOM_MAX: 3.0,
} as const;
